spring.application.name=apigateway
server.port=8080

# Route configuration
spring.cloud.gateway.mvc.routes[0].id=productservice
spring.cloud.gateway.mvc.routes[0].uri=lb://productservice
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/products/**

# Discovery locator
spring.cloud.gateway.mvc.discovery.locator.enabled=true
spring.cloud.gateway.mvc.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.mvc.routes[1].id=productservice-docs
spring.cloud.gateway.mvc.routes[1].uri=lb://productservice
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/swagger-ui/**,/api-docs/**,/swagger-ui.html